FROM registry.access.redhat.com/ubi8/python-39
#FROM registry.redhat.io/ubi8/nodejs-16:latest
#FROM registry.access.redhat.com/ubi8/nodejs-16:latest

USER root

RUN yum update -y && yum clean all

RUN pip install -U pip setuptools wheel && \
    pip install -U mod_wsgi supervisor && \
    pip install -U notebook jupyterhub jupyterlab jupyter_server jupyter_core jupyter_client IPython ipykernel traitlets nbclient nbconvert nbformat dask tornado distributed && \
    npm cache clean --force

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts

USER 1001

LABEL io.k8s.description="S2I builder for custom Jupyter notebooks." \
      io.k8s.display-name="Jupyter Notebook" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jupyter" \
      io.openshift.s2i.scripts-url="image:///opt/app-root/builder"

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
